# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlateSpotter' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for PlateSpotter

  target 'PlateSpotterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlateSpotterUITests' do
    # Pods for testing
  end

end
